# GitHub configuration
# Specifies backend protocol and publication branch
backend:
  # name: git-gateway # open-source API that acts as a proxy between authenticated users of site and repo
  # branch: master # Branch to update (optional; defaults to master)
  name: github
  repo: arbolitoloco/bioinformatica
# Adds interface for drafting, reviewing, and approving posts
publish_mode: editorial_workflow
media_folder: "assets/images/uploads" # Media files will be stored in the repo under assets/images/uploads
collections:
  - name: "docs" # Used in routes, e.g., /admin/collections/blog
    label: "Textos" # Used in the UI
    folder: "docs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Categoria", name: "layout", widget: "hidden", default: "default"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Ordem no menu", name: "nav_order", widget: "number"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}